### ISSUE TITLE
(32bit) Panic on winpty.Open

### ISSUE THREAD

**Issue by KnutHelland** [iamacarpet/go-winpty#1]
Hi!

Your work here looks very interesting, but I haven't managed to make it run. It panics in the call to `winpty.Open`. I'm not experienced enough to debug the interop with the dll and I can't find anyting wrong in your code. But the only output I manage to get when I'm using your library is the following panic.

Btw: this is 32 bit

Do you have any idea what can be the problem?

```
C:\Users\IEUser\Desktop>web-pty.exe
Exception 0xc0000005 0x1 0x452c44 0x6db3d1a0
PC=0x6db3d1a0

syscall.Syscall(0x6db313d9, 0x2, 0x0, 0x0, 0x0, 0x11854780, 0x0, 0x1184a8c0)
        /usr/local/Cellar/go/1.7.3/libexec/src/runtime/syscall_windows.go:163 +0
x4a
syscall.(*Proc).Call(0x118c7c30, 0x118c7c18, 0x2, 0x2, 0x8, 0x612980, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.3/libexec/src/syscall/dll_windows.go:149 +0x28c

syscall.(*LazyProc).Call(0x118cac60, 0x118c7c18, 0x2, 0x2, 0x1, 0x1, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.3/libexec/src/syscall/dll_windows.go:304 +0x54
github.com/iamacarpet/go-winpty.Open(0x0, 0x0, 0x654058, 0x3, 0x0, 0x0, 0x0)
        /Users/knut/go/src/github.com/iamacarpet/go-winpty/winpty.go:27 +0x127
main.(*wsPty).Start(0x1185e5b0)
        /Users/knut/go/src/github.com/iamacarpet/go-winpty/example/server.go:56
+0x4f
main.ptyHandler(0x735c80, 0x11874870, 0x11840600)
        /Users/knut/go/src/github.com/iamacarpet/go-winpty/example/server.go:79
+0x155
net/http.HandlerFunc.ServeHTTP(0x67e998, 0x735c80, 0x11874870, 0x11840600)
        /usr/local/Cellar/go/1.7.3/libexec/src/net/http/server.go:1726 +0x34
net/http.(*ServeMux).ServeHTTP(0x74d740, 0x735c80, 0x11874870, 0x11840600)
        /usr/local/Cellar/go/1.7.3/libexec/src/net/http/server.go:2022 +0x133
net/http.serverHandler.ServeHTTP(0x1184c230, 0x735c80, 0x11874870, 0x11840600)
        /usr/local/Cellar/go/1.7.3/libexec/src/net/http/server.go:2202 +0x136
net/http.(*conn).serve(0x1184a780, 0x736180, 0x118ca960)
        /usr/local/Cellar/go/1.7.3/libexec/src/net/http/server.go:1579 +0xe86
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.7.3/libexec/src/net/http/server.go:2293 +0x489

goroutine 1 [IO wait]:
net.runtime_pollWait(0x31b24fd8, 0x72, 0x118c7b84)
        /usr/local/Cellar/go/1.7.3/libexec/src/runtime/netpoll.go:160 +0x55
net.(*pollDesc).wait(0x118907d0, 0x72, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.3/libexec/src/net/fd_poll_runtime.go:73 +0x35
net.(*ioSrv).ExecIO(0x1185e530, 0x11890738, 0x654cf9, 0x8, 0x118c7b90, 0x11890c4
0, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.3/libexec/src/net/fd_windows.go:171 +0x122
net.(*netFD).acceptOne(0x11890700, 0x11890b60, 0x2, 0x2, 0x11890738, 0x67cbab, 0
x0, 0x0)
        /usr/local/Cellar/go/1.7.3/libexec/src/net/fd_windows.go:529 +0x1d4
net.(*netFD).accept(0x11890700, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.3/libexec/src/net/fd_windows.go:559 +0x133
net.(*TCPListener).accept(0x1185e540, 0xe8e54a3f, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.3/libexec/src/net/tcpsock_posix.go:132 +0x2d
net.(*TCPListener).AcceptTCP(0x1185e540, 0x44e0a0, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.3/libexec/src/net/tcpsock.go:209 +0x8f
net/http.tcpKeepAliveListener.Accept(0x1185e540, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.3/libexec/src/net/http/server.go:2608 +0x3d
net/http.(*Server).Serve(0x1184c230, 0x735d00, 0x1185e540, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.3/libexec/src/net/http/server.go:2273 +0x216
net/http.(*Server).ListenAndServe(0x1184c230, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.3/libexec/src/net/http/server.go:2219 +0xd9
net/http.ListenAndServe(0x654451, 0x5, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.3/libexec/src/net/http/server.go:2351 +0x7a
main.main()
        /Users/knut/go/src/github.com/iamacarpet/go-winpty/example/server.go:191
 +0x110

goroutine 5 [IO wait]:
net.runtime_pollWait(0x31b24f60, 0x72, 0x118c7b80)
        /usr/local/Cellar/go/1.7.3/libexec/src/runtime/netpoll.go:160 +0x55
net.(*pollDesc).wait(0x11890990, 0x72, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.3/libexec/src/net/fd_poll_runtime.go:73 +0x35
net.(*ioSrv).ExecIO(0x1185e530, 0x118908f8, 0x654b26, 0x7, 0x67e9b4, 0xfc2, 0x0,
 0x0)
        /usr/local/Cellar/go/1.7.3/libexec/src/net/fd_windows.go:171 +0x122
net.(*netFD).Read(0x118908c0, 0x11897000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.3/libexec/src/net/fd_windows.go:426 +0x129
net.(*conn).Read(0x1185e558, 0x11897000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.3/libexec/src/net/net.go:173 +0xa9
net/http.(*connReader).Read(0x118ca500, 0x11897000, 0x1000, 0x1000, 0x0, 0x0, 0x
0)
        /usr/local/Cellar/go/1.7.3/libexec/src/net/http/server.go:586 +0x189
bufio.(*Reader).fill(0x11848570)
        /usr/local/Cellar/go/1.7.3/libexec/src/bufio/bufio.go:97 +0x172
bufio.(*Reader).ReadSlice(0x11848570, 0x67cc0a, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.3/libexec/src/bufio/bufio.go:330 +0x1b4
bufio.(*Reader).ReadLine(0x11848570, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.3/libexec/src/bufio/bufio.go:359 +0x4b
net/textproto.(*Reader).readLineSlice(0x118ca560, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.3/libexec/src/net/textproto/reader.go:55 +0x59
net/textproto.(*Reader).ReadLine(0x118ca560, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.3/libexec/src/net/textproto/reader.go:36 +0x39
net/http.readRequest(0x11848570, 0x655900, 0x11840580, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.3/libexec/src/net/http/request.go:793 +0x9a
net/http.(*conn).readRequest(0x1184a500, 0x736180, 0x118ca540, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.3/libexec/src/net/http/server.go:765 +0x3c0
net/http.(*conn).serve(0x1184a500, 0x736180, 0x118ca540)
        /usr/local/Cellar/go/1.7.3/libexec/src/net/http/server.go:1532 +0x96c
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.7.3/libexec/src/net/http/server.go:2293 +0x489
eax     0x452c44
ebx     0x118604b0
ecx     0x0
edx     0x11869b3c
edi     0x38ff3c
esi     0x11869b80
ebp     0x38ff2c
esp     0x38ff0c
eip     0x6db3d1a0
eflags  0x10206
cs      0x1b
fs      0x3b
gs      0x0
```

**Comment by iamacarpet** [comment]
Hello @KnutHelland,

Just tried this myself on 32bit and got the same issue, so it isn't just you.

The bad news is, I can't see what the problem is so far.

I'd expect if it works on 64bit (just confirmed it does) and not on 32bit, it would be a type difference.
I've checked around and it looks like we are using all int32 values anyway, so nothing obvious.

Will take another look properly when I've got some more time.

Regards,
iamacarpet

**Comment by KnutHelland** [comment]
Hello!

Thank you for your time and response!

The exception is documented here: https://msdn.microsoft.com/en-us/library/cc704588.aspx

> 0xC0000005
> STATUS_ACCESS_VIOLATION
> The instruction at 0x%08lx referenced memory at 0x%08lx. The memory could not be %s.

The program probably tries to access memory that it isn't allowed to.

This may be related to this (old) issue about DLLs and go: https://github.com/golang/go/issues/9457 I tried the solution (adding `import _ "runtime/cgo"`) without luck.

**Comment by pieter-lazzaro** [comment]
This is caused by because the flag param to winpty_config_new is a UINT64. because uintptr's are 32bits on 386 it is combining the first to parameters. You can work around it by manually adding another uintptr after the first argument to pad the value.

I will put in a PR later when I get some time.
